# 1. Download and unzip project files
if(!file.exists("./data")) {dir.create("./data")}
fileUrl <- "http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
temp <- tempfile()
download.file(fileUrl,temp, mode="wb")
unzip(temp,exdir="./data")

# 2. Read files into R
features <- read.table("./data/UCI HAR Dataset/features.txt")
activity_labels <- read.table("./data/UCI HAR Dataset/activity_labels.txt",col.names=c("activity","activity_label"))
subject_test <- read.table("./data/UCI HAR Dataset/test/subject_test.txt",col.names="subject")
X_test <- read.table("./data/UCI HAR Dataset/test/X_test.txt",col.names=make.names(features[,2]))
y_test <- read.table("./data/UCI HAR Dataset/test/y_test.txt",col.names="activity")
subject_train <- read.table("./data/UCI HAR Dataset/train/subject_train.txt",col.names="subject")
X_train <- read.table("./data/UCI HAR Dataset/train/X_train.txt",col.names=make.names(features[,2]))
y_train <- read.table("./data/UCI HAR Dataset/train/y_train.txt",col.names="activity")

# 3. Merge the training and test sets into one dataset
y_test_labeled <- merge(y_test,activity_labels,by.x="activity",by.y="activity")
y_train_labeled <- merge(y_train,activity_labels,by.x="activity",by.y="activity")
total_test <- cbind(subject_test,y_test_labeled,X_test)
total_train <- cbind(subject_train,y_train_labeled,X_train)
dataset <- rbind(total_test,total_train)

# 4. Extract measurements on the mean and standard deviation (features with mean() and std() at the end) and rename columns
dataset2 <- dataset[,c( "subject",
                        "activity_label",
                        "tBodyAcc.mean...X",
                        "tBodyAcc.mean...Y",
                        "tBodyAcc.mean...Z",
                        "tBodyAcc.std...X",
                        "tBodyAcc.std...Y",
                        "tBodyAcc.std...Z",
                        "tGravityAcc.mean...X",
                        "tGravityAcc.mean...Y",
                        "tGravityAcc.mean...Z",
                        "tGravityAcc.std...X",
                        "tGravityAcc.std...Y",
                        "tGravityAcc.std...Z",
                        "tBodyAccJerk.mean...X",
                        "tBodyAccJerk.mean...Y",
                        "tBodyAccJerk.mean...Z",
                        "tBodyAccJerk.std...X",
                        "tBodyAccJerk.std...Y",
                        "tBodyAccJerk.std...Z",
                        "tBodyGyro.mean...X",
                        "tBodyGyro.mean...Y",
                        "tBodyGyro.mean...Z",
                        "tBodyGyro.std...X",
                        "tBodyGyro.std...Y",
                        "tBodyGyro.std...Z",
                        "tBodyGyroJerk.mean...X",
                        "tBodyGyroJerk.mean...Y",
                        "tBodyGyroJerk.mean...Z",
                        "tBodyGyroJerk.std...X",
                        "tBodyGyroJerk.std...Y",
                        "tBodyGyroJerk.std...Z",
                        "tBodyAccMag.mean..",
                        "tBodyAccMag.std..",
                        "tGravityAccMag.mean..",
                        "tGravityAccMag.std..",
                        "tBodyAccJerkMag.mean..",
                        "tBodyAccJerkMag.std..",
                        "tBodyGyroMag.mean..",
                        "tBodyGyroMag.std..",
                        "tBodyGyroJerkMag.mean..",
                        "tBodyGyroJerkMag.std..",
                        "fBodyAcc.mean...X",
                        "fBodyAcc.mean...Y",
                        "fBodyAcc.mean...Z",
                        "fBodyAcc.std...X",
                        "fBodyAcc.std...Y",
                        "fBodyAcc.std...Z",
                        "fBodyAccJerk.mean...X",
                        "fBodyAccJerk.mean...Y",
                        "fBodyAccJerk.mean...Z",
                        "fBodyAccJerk.std...X",
                        "fBodyAccJerk.std...Y",
                        "fBodyAccJerk.std...Z",
                        "fBodyGyro.mean...X",
                        "fBodyGyro.mean...Y",
                        "fBodyGyro.mean...Z",
                        "fBodyGyro.std...X",
                        "fBodyGyro.std...Y",
                        "fBodyGyro.std...Z",
                        "fBodyAccMag.mean..",
                        "fBodyAccMag.std..",
                        "fBodyBodyAccJerkMag.mean..",
                        "fBodyBodyAccJerkMag.std..",
                        "fBodyBodyGyroMag.mean..",
                        "fBodyBodyGyroMag.std..",
                        "fBodyBodyGyroJerkMag.mean..",
                        "fBodyBodyGyroJerkMag.std..")]
names(dataset2) <- c("subject",
                     "activity_label",
                     "tBodyAcc_mean_X",
                     "tBodyAcc_mean_Y",
                     "tBodyAcc_mean_Z",
                     "tBodyAcc_std_X",
                     "tBodyAcc_std_Y",
                     "tBodyAcc_std_Z",
                     "tGravityAcc_mean_X",
                     "tGravityAcc_mean_Y",
                     "tGravityAcc_mean_Z",
                     "tGravityAcc_std_X",
                     "tGravityAcc_std_Y",
                     "tGravityAcc_std_Z",
                     "tBodyAccJerk_mean_X",
                     "tBodyAccJerk_mean_Y",
                     "tBodyAccJerk_mean_Z",
                     "tBodyAccJerk_std_X",
                     "tBodyAccJerk_std_Y",
                     "tBodyAccJerk_std_Z",
                     "tBodyGyro_mean_X",
                     "tBodyGyro_mean_Y",
                     "tBodyGyro_mean_Z",
                     "tBodyGyro_std_X",
                     "tBodyGyro_std_Y",
                     "tBodyGyro_std_Z",
                     "tBodyGyroJerk_mean_X",
                     "tBodyGyroJerk_mean_Y",
                     "tBodyGyroJerk_mean_Z",
                     "tBodyGyroJerk_std_X",
                     "tBodyGyroJerk_std_Y",
                     "tBodyGyroJerk_std_Z",
                     "tBodyAccMag_mean",
                     "tBodyAccMag_std_",
                     "tGravityAccMag_mean",
                     "tGravityAccMag_std",
                     "tBodyAccJerkMag_mean",
                     "tBodyAccJerkMag_std",
                     "tBodyGyroMag_mean",
                     "tBodyGyroMag_std",
                     "tBodyGyroJerkMag_mean",
                     "tBodyGyroJerkMag_std",
                     "fBodyAcc_mean_X",
                     "fBodyAcc_mean_Y",
                     "fBodyAcc_mean_Z",
                     "fBodyAcc_std_X",
                     "fBodyAcc_std_Y",
                     "fBodyAcc_std_Z",
                     "fBodyAccJerk_mean_X",
                     "fBodyAccJerk_mean_Y",
                     "fBodyAccJerk_mean_Z",
                     "fBodyAccJerk_std_X",
                     "fBodyAccJerk_std_Y",
                     "fBodyAccJerk_std_Z",
                     "fBodyGyro_mean_X",
                     "fBodyGyro_mean_Y",
                     "fBodyGyro_mean_Z",
                     "fBodyGyro_std_X",
                     "fBodyGyro_std_Y",
                     "fBodyGyro_std_Z",
                     "fBodyAccMag_mean",
                     "fBodyAccMag_std",
                     "fBodyBodyAccJerkMag_mean",
                     "fBodyBodyAccJerkMag_std",
                     "fBodyBodyGyroMag_mean",
                     "fBodyBodyGyroMag_std",
                     "fBodyBodyGyroJerkMag_mean",
                     "fBodyBodyGyroJerkMag_std")

# 5. Create an independent tidy dataset with the average of each variable for each activity and each subject
library(reshape)
molten <- melt(dataset2, id.vars = c("subject", "activity_label"))
tidy_dataset <- cast(subject + activity_label ~ variable, data = molten, fun = mean)
names(tidy_dataset) <- c("subject",
                         "activity_label",
                         "mean.tBodyAcc_mean_X",
                         "mean.tBodyAcc_mean_Y",
                         "mean.tBodyAcc_mean_Z",
                         "mean.tBodyAcc_std_X",
                         "mean.tBodyAcc_std_Y",
                         "mean.tBodyAcc_std_Z",
                         "mean.tGravityAcc_mean_X",
                         "mean.tGravityAcc_mean_Y",
                         "mean.tGravityAcc_mean_Z",
                         "mean.tGravityAcc_std_X",
                         "mean.tGravityAcc_std_Y",
                         "mean.tGravityAcc_std_Z",
                         "mean.tBodyAccJerk_mean_X",
                         "mean.tBodyAccJerk_mean_Y",
                         "mean.tBodyAccJerk_mean_Z",
                         "mean.tBodyAccJerk_std_X",
                         "mean.tBodyAccJerk_std_Y",
                         "mean.tBodyAccJerk_std_Z",
                         "mean.tBodyGyro_mean_X",
                         "mean.tBodyGyro_mean_Y",
                         "mean.tBodyGyro_mean_Z",
                         "mean.tBodyGyro_std_X",
                         "mean.tBodyGyro_std_Y",
                         "mean.tBodyGyro_std_Z",
                         "mean.tBodyGyroJerk_mean_X",
                         "mean.tBodyGyroJerk_mean_Y",
                         "mean.tBodyGyroJerk_mean_Z",
                         "mean.tBodyGyroJerk_std_X",
                         "mean.tBodyGyroJerk_std_Y",
                         "mean.tBodyGyroJerk_std_Z",
                         "mean.tBodyAccMag_mean",
                         "mean.tBodyAccMag_std_",
                         "mean.tGravityAccMag_mean",
                         "mean.tGravityAccMag_std",
                         "mean.tBodyAccJerkMag_mean",
                         "mean.tBodyAccJerkMag_std",
                         "mean.tBodyGyroMag_mean",
                         "mean.tBodyGyroMag_std",
                         "mean.tBodyGyroJerkMag_mean",
                         "mean.tBodyGyroJerkMag_std",
                         "mean.fBodyAcc_mean_X",
                         "mean.fBodyAcc_mean_Y",
                         "mean.fBodyAcc_mean_Z",
                         "mean.fBodyAcc_std_X",
                         "mean.fBodyAcc_std_Y",
                         "mean.fBodyAcc_std_Z",
                         "mean.fBodyAccJerk_mean_X",
                         "mean.fBodyAccJerk_mean_Y",
                         "mean.fBodyAccJerk_mean_Z",
                         "mean.fBodyAccJerk_std_X",
                         "mean.fBodyAccJerk_std_Y",
                         "mean.fBodyAccJerk_std_Z",
                         "mean.fBodyGyro_mean_X",
                         "mean.fBodyGyro_mean_Y",
                         "mean.fBodyGyro_mean_Z",
                         "mean.fBodyGyro_std_X",
                         "mean.fBodyGyro_std_Y",
                         "mean.fBodyGyro_std_Z",
                         "mean.fBodyAccMag_mean",
                         "mean.fBodyAccMag_std",
                         "mean.fBodyBodyAccJerkMag_mean",
                         "mean.fBodyBodyAccJerkMag_std",
                         "mean.fBodyBodyGyroMag_mean",
                         "mean.fBodyBodyGyroMag_std",
                         "mean.fBodyBodyGyroJerkMag_mean",
                         "mean.fBodyBodyGyroJerkMag_std")

# 6. Save the new dataset in the "date" folder in the working directory
write.table(tidy_dataset,file="./data/tidy_dataset.txt")
